### ISSUE TITLE
Request: `ng add` use devDependencies 

### ISSUE THREAD

**Issue by xmlking** [d-koppenhagen/ngx-semantic-version#18]
# 🧩 Feature

## What feature / part will be affected
 Currently, ng add `ngx-semantic-version` command adds `ngx-semantic-version` package into dependencies in package.json.

I think it will be better than adds it into devDependencies because `ngx-semantic-version` is not needed in runtime.

In the latest versions of the CLI ng-add packages can be added to devDependencies and this package is perfect for such use case since it's only needed for development.

See: https://github.com/angular/angular-cli/pull/15815

**Comment by d-koppenhagen** [comment]
Thanks for the suggestion. I have been implemented for version2 which is available with angular9:

```bash
ng add ngx-semantic-version@2.0.0-beta.1
```
