### ISSUE TITLE
Make package selection configurable

### ISSUE THREAD

**Issue by fmalcher** [d-koppenhagen/ngx-semantic-version#9]
Provide flags that disable adding specific packages, e.g. if I don't want `standard-version`

**Comment by d-koppenhagen** [comment]
Seems legit.
Thanks for pointing this out

**Comment by d-koppenhagen** [comment]
I think there are some installations that can be skipped but not all (as they are essential):

### skippable packages (but included by default)
- commitizen
- standard-version
- (husky, if just using commitlint without hooks)

### essential (not skippable)
- commitlint

I will include flags for skipping the packages like that:

```bash
ng add ngx-semantic-version --commitizen false --husky false --standard-version false
```
